# Generated by Django 4.2.13 on 2024-07-23 08:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='upload/image/', validators=[functools.partial(page.models.validate_max_file_size, *(), **{'max_size': 10485760}), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='upload/image/', validators=[functools.partial(page.models.validate_max_file_size, *(), **{'max_size': 5242880}), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('qr_code', models.ImageField(upload_to='uploads/image/', validators=[functools.partial(page.models.validate_max_file_size, *(), **{'max_size': 5242880}), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('cv', models.FileField(blank=True, null=True, upload_to='uploads/file/', validators=[functools.partial(page.models.validate_max_file_size, *(), **{'max_size': 10485760}), django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('identification', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(max_length=1024)),
                ('max_address_count', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('max_image_count', models.SmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('max_comminucation_count', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(20)])),
                ('publish', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=30)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('is_active_by_admin', models.BooleanField(default=True)),
                ('is_active_by_user', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(upload_to='upload/image/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='Comminucation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('phone', 'phone'), ('instagram', 'instagram'), ('telegram', 'telegram'), ('whatsapp', 'whatsapp'), ('eitaa', 'eitaa'), ('rubika', 'rubika'), ('bale', 'bale'), ('gap', 'gap'), ('igap', 'igap'), ('gmail', 'gmail'), ('outlook', 'outlook'), ('yahoo', 'yahoo'), ('email', 'email'), ('linkedin', 'linkedin'), ('github', 'github'), ('website', 'website')], max_length=30)),
                ('link', models.CharField(max_length=128)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.TextField(max_length=1024)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
        ),
    ]
