# Generated by Django 4.2.13 on 2024-07-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='max_num_of_addresses',
            new_name='max_address_count',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='max_num_of_comminucations',
            new_name='max_comminucation_count',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='max_num_of_images',
            new_name='max_image_count',
        ),
    ]
